AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.7
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
